//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDYNESmsSample.SmsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSResponse", Namespace="http://sms2.cdyne.com")]
    [System.SerializableAttribute()]
    public partial class SMSResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CancelledField;
        
        private System.Guid MessageIDField;
        
        private bool QueuedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIDField;
        
        private CDYNESmsSample.SmsService.SMSErrors SMSErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CDYNESmsSample.SmsService.SMSIncomingMessage[] SMSIncomingMessagesField;
        
        private bool SentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SentDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Cancelled {
            get {
                return this.CancelledField;
            }
            set {
                if ((this.CancelledField.Equals(value) != true)) {
                    this.CancelledField = value;
                    this.RaisePropertyChanged("Cancelled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((this.MessageIDField.Equals(value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Queued {
            get {
                return this.QueuedField;
            }
            set {
                if ((this.QueuedField.Equals(value) != true)) {
                    this.QueuedField = value;
                    this.RaisePropertyChanged("Queued");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceID {
            get {
                return this.ReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIDField, value) != true)) {
                    this.ReferenceIDField = value;
                    this.RaisePropertyChanged("ReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public CDYNESmsSample.SmsService.SMSErrors SMSError {
            get {
                return this.SMSErrorField;
            }
            set {
                if ((this.SMSErrorField.Equals(value) != true)) {
                    this.SMSErrorField = value;
                    this.RaisePropertyChanged("SMSError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CDYNESmsSample.SmsService.SMSIncomingMessage[] SMSIncomingMessages {
            get {
                return this.SMSIncomingMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSIncomingMessagesField, value) != true)) {
                    this.SMSIncomingMessagesField = value;
                    this.RaisePropertyChanged("SMSIncomingMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Sent {
            get {
                return this.SentField;
            }
            set {
                if ((this.SentField.Equals(value) != true)) {
                    this.SentField = value;
                    this.RaisePropertyChanged("Sent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SentDateTime {
            get {
                return this.SentDateTimeField;
            }
            set {
                if ((this.SentDateTimeField.Equals(value) != true)) {
                    this.SentDateTimeField = value;
                    this.RaisePropertyChanged("SentDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSErrors", Namespace="http://sms2.cdyne.com")]
    public enum SMSErrors : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoError = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STOPfromPhoneNumber = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LicenseKeyInvalid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhoneNumberInvalid = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MessageInvalid = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScheduledDateTimeIsNotUTC = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAssignedDID = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContactCdyneAccountSuspended = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSIncomingMessage", Namespace="http://sms2.cdyne.com")]
    [System.SerializableAttribute()]
    public partial class SMSIncomingMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IncomingMessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MatchedMessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ResponseReceiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToPhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromPhoneNumber {
            get {
                return this.FromPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FromPhoneNumberField, value) != true)) {
                    this.FromPhoneNumberField = value;
                    this.RaisePropertyChanged("FromPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IncomingMessageID {
            get {
                return this.IncomingMessageIDField;
            }
            set {
                if ((this.IncomingMessageIDField.Equals(value) != true)) {
                    this.IncomingMessageIDField = value;
                    this.RaisePropertyChanged("IncomingMessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MatchedMessageID {
            get {
                return this.MatchedMessageIDField;
            }
            set {
                if ((this.MatchedMessageIDField.Equals(value) != true)) {
                    this.MatchedMessageIDField = value;
                    this.RaisePropertyChanged("MatchedMessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ResponseReceiveDate {
            get {
                return this.ResponseReceiveDateField;
            }
            set {
                if ((this.ResponseReceiveDateField.Equals(value) != true)) {
                    this.ResponseReceiveDateField = value;
                    this.RaisePropertyChanged("ResponseReceiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToPhoneNumber {
            get {
                return this.ToPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ToPhoneNumberField, value) != true)) {
                    this.ToPhoneNumberField = value;
                    this.RaisePropertyChanged("ToPhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSAdvancedRequest", Namespace="http://schemas.datacontract.org/2004/07/SmsWS")]
    [System.SerializableAttribute()]
    public partial class SMSAdvancedRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LicenseKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CDYNESmsSample.SmsService.SMSRequest[] SMSRequestsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LicenseKey {
            get {
                return this.LicenseKeyField;
            }
            set {
                if ((this.LicenseKeyField.Equals(value) != true)) {
                    this.LicenseKeyField = value;
                    this.RaisePropertyChanged("LicenseKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CDYNESmsSample.SmsService.SMSRequest[] SMSRequests {
            get {
                return this.SMSRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSRequestsField, value) != true)) {
                    this.SMSRequestsField = value;
                    this.RaisePropertyChanged("SMSRequests");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSRequest", Namespace="http://sms2.cdyne.com")]
    [System.SerializableAttribute()]
    public partial class SMSRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedDIDField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PhoneNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ScheduledDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusPostBackURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AssignedDID {
            get {
                return this.AssignedDIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedDIDField, value) != true)) {
                    this.AssignedDIDField = value;
                    this.RaisePropertyChanged("AssignedDID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PhoneNumbers {
            get {
                return this.PhoneNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumbersField, value) != true)) {
                    this.PhoneNumbersField = value;
                    this.RaisePropertyChanged("PhoneNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceID {
            get {
                return this.ReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIDField, value) != true)) {
                    this.ReferenceIDField = value;
                    this.RaisePropertyChanged("ReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime ScheduledDateTime {
            get {
                return this.ScheduledDateTimeField;
            }
            set {
                if ((this.ScheduledDateTimeField.Equals(value) != true)) {
                    this.ScheduledDateTimeField = value;
                    this.RaisePropertyChanged("ScheduledDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusPostBackURL {
            get {
                return this.StatusPostBackURLField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusPostBackURLField, value) != true)) {
                    this.StatusPostBackURLField = value;
                    this.RaisePropertyChanged("StatusPostBackURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sms2.cdyne.com", ConfigurationName="SmsService.Isms")]
    public interface Isms {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/SimpleSMSsend", ReplyAction="http://sms2.cdyne.com/Isms/SimpleSMSsendResponse")]
        CDYNESmsSample.SmsService.SMSResponse SimpleSMSsend(string PhoneNumber, string Message, System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/SimpleSMSsendWithPostback", ReplyAction="http://sms2.cdyne.com/Isms/SimpleSMSsendWithPostbackResponse")]
        CDYNESmsSample.SmsService.SMSResponse SimpleSMSsendWithPostback(string PhoneNumber, string Message, System.Guid LicenseKey, string StatusPostBackURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/AdvancedSMSsend", ReplyAction="http://sms2.cdyne.com/Isms/AdvancedSMSsendResponse")]
        CDYNESmsSample.SmsService.SMSResponse[] AdvancedSMSsend(CDYNESmsSample.SmsService.SMSAdvancedRequest AdvancedRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetMessageStatus", ReplyAction="http://sms2.cdyne.com/Isms/GetMessageStatusResponse")]
        CDYNESmsSample.SmsService.SMSResponse GetMessageStatus(System.Guid MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetMessageStatusByReferenceID", ReplyAction="http://sms2.cdyne.com/Isms/GetMessageStatusByReferenceIDResponse")]
        CDYNESmsSample.SmsService.SMSResponse[] GetMessageStatusByReferenceID(string ReferenceID, System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetUnreadIncomingMessages", ReplyAction="http://sms2.cdyne.com/Isms/GetUnreadIncomingMessagesResponse")]
        CDYNESmsSample.SmsService.SMSIncomingMessage[] GetUnreadIncomingMessages(System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/CancelMessage", ReplyAction="http://sms2.cdyne.com/Isms/CancelMessageResponse")]
        bool CancelMessage(System.Guid MessageID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsmsChannel : CDYNESmsSample.SmsService.Isms, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsmsClient : System.ServiceModel.ClientBase<CDYNESmsSample.SmsService.Isms>, CDYNESmsSample.SmsService.Isms {
        
        public IsmsClient() {
        }
        
        public IsmsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsmsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsmsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsmsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CDYNESmsSample.SmsService.SMSResponse SimpleSMSsend(string PhoneNumber, string Message, System.Guid LicenseKey) {
            return base.Channel.SimpleSMSsend(PhoneNumber, Message, LicenseKey);
        }
        
        public CDYNESmsSample.SmsService.SMSResponse SimpleSMSsendWithPostback(string PhoneNumber, string Message, System.Guid LicenseKey, string StatusPostBackURL) {
            return base.Channel.SimpleSMSsendWithPostback(PhoneNumber, Message, LicenseKey, StatusPostBackURL);
        }
        
        public CDYNESmsSample.SmsService.SMSResponse[] AdvancedSMSsend(CDYNESmsSample.SmsService.SMSAdvancedRequest AdvancedRequest) {
            return base.Channel.AdvancedSMSsend(AdvancedRequest);
        }
        
        public CDYNESmsSample.SmsService.SMSResponse GetMessageStatus(System.Guid MessageID) {
            return base.Channel.GetMessageStatus(MessageID);
        }
        
        public CDYNESmsSample.SmsService.SMSResponse[] GetMessageStatusByReferenceID(string ReferenceID, System.Guid LicenseKey) {
            return base.Channel.GetMessageStatusByReferenceID(ReferenceID, LicenseKey);
        }
        
        public CDYNESmsSample.SmsService.SMSIncomingMessage[] GetUnreadIncomingMessages(System.Guid LicenseKey) {
            return base.Channel.GetUnreadIncomingMessages(LicenseKey);
        }
        
        public bool CancelMessage(System.Guid MessageID) {
            return base.Channel.CancelMessage(MessageID);
        }
    }
}
